In [5]:
!pip install numpy

In [6]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [9]:
zeroes=np.zeros((3,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones=np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [11]:
range_array=np.arange(1,10,2)
print(range_array)
#it will build an array of range 3 by skipping 2

[1 3 5 7 9]


In [16]:
linspace_array=np.linspace(0,1,5)
print(linspace_array)
#create intervals of 5 within

[0.   0.25 0.5  0.75 1.  ]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])
reshaped=arr.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr=np.array([1,2,3])
expanded=arr[:,np.newaxis]
print(expanded)


[[1]
 [2]
 [3]]


In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [23]:
arr=np.array([4,16,25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

[2. 4. 5.]
45
15.0
25


In [31]:
arr=np.array([10,20,30,40,50,60])
print(arr[2])
print(arr[-1])

30
60


In [32]:
print(arr[1:4])

[20 30 40]


In [33]:
print(arr[3:])

[40 50 60]


In [34]:
reshaped=arr.reshape(2,3)
print(reshaped)

[[10 20 30]
 [40 50 60]]


In [36]:
a=np.arange(1,6)
b=np.arange(6,11)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [38]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
transpose=matrix.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
matrix1=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [42]:
print("addition:\n",matrix+matrix1)
print("multiplication:\n",matrix*matrix1)

addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [43]:
#array and scalar broadcasting
arr=np.array([1,2,3])
print(arr+10)

[11 12 13]


In [44]:
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([1,0,1])
print(matrix+vector)

[[2 2 4]
 [5 5 7]]


In [47]:
#filters

In [50]:
arr=np.array([1,2,3,4,5,6])
even=arr[arr % 2==0]
print("evens:",even)
arr[arr>3]=0 # array values > 3 it updated to 0
print("modified array:",arr)


evens: [2 4 6]
modified array: [1 2 3 0 0 0]


In [81]:
#setting random seeds
np.random.seed(42)
random_array=np.random.rand(3,3)
print("random array\n",random_array)




random array
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [82]:
random_array=np.random.rand(3,3)
print("random array\n",random_array)
random_integers=np.random.randint(0,10,size=(2,3))
print(random_integers)


random array
 [[0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[[8 0 9]
 [2 6 3]]
